# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20171004_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
    ]
