# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20171005_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_no',
            field=models.CharField(max_length=30, verbose_name='Заводской номер'),
        ),
    ]
