# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20171009_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('type',), 'verbose_name_plural': 'Оборудование'},
        ),
    ]
