# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripsheet',
            options={'ordering': ('-work_end_time',), 'verbose_name': 'Рабочие часы'},
        ),
        migrations.AlterField(
            model_name='tripsheet',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='tripsheet',
            name='work_end_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Работа зажешина'),
        ),
        migrations.AlterField(
            model_name='tripsheet',
            name='working_hours_after',
            field=models.IntegerField(verbose_name='Рабочие часы после работы'),
        ),
        migrations.AlterField(
            model_name='tripsheet',
            name='working_hours_before',
            field=models.IntegerField(verbose_name='Рабочие часы в начале работы'),
        ),
    ]
