# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripsheet', '0002_auto_20171009_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripsheet',
            options={'ordering': ('-work_end_time',), 'verbose_name': 'Рабочие часы', 'verbose_name_plural': 'Рабочие часы'},
        ),
        migrations.AlterField(
            model_name='tripsheet',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='Оборудование'),
        ),
    ]
